### PR TITLE
Add liveCSS option

### PR DESCRIPTION
**Pull request by peterwmwong**
... for the unfortunate souls that rely on this livereload flag to do a full refresh on CSS file changes.

### CODE REVIEW

**Comment by vohof** [comment]
What is the flag for?

**Comment by peterwmwong** [comment]
@vohof With `liveCSS=false`, CSS file changes cause a full page refresh (like JS file changes).  It's part of the protocol (http://feedback.livereload.com/knowledgebase/articles/86174-livereload-protocol).  I personally need this option when working with WebComponents.

I believe options like these used to work in V2, because options were passed through to tinylr: https://github.com/vohof/gulp-livereload/blob/master/gulp-livereload.js#L67

**Comment by vohof** [comment]
@peterwmwong Could you try the test branch? You would have to pass tinylr specific options like so:

```
glr.listen({ tinylr: { liveCSS: false } });
```

I think this would be cleaner so it won't mix up with gulp-livereload-spefic options.

**Comment by vohof** [comment]
Fixed in a1d6017f0f0e8

**Comment by peterwmwong** [comment]
@vohof The fix works for me. Thanks for the quick turnaround!

**Pull request closed without merging**
