### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by wiseguy12851**
I've made some improvements if your interested. I found the README to be very vague so I updated it with a lot more detail and completed out the API details and such. I also fixed the hardcoded index.html in reload() so that it now supports a variable reload() page. Documented the code a bit more.

### CODE REVIEW

**Comment by vohof** [comment]
OH wow, thank you very much!

One note, it's `option.reloadFile` on README but  `option.reloadPage` on index.js. Can you update that before I merge?

**Comment by wiseguy12851** [comment]
Thanks, I missed that typo and have updated the README file to reflect the index.js

**Comment by vohof** [comment]
Awesome! Thank you :sparkles: :sparkles:

**Comment by wiseguy12851** [comment]
Your welcome

**Pull request merged**
