### PR TITLE
correct alternative commented example

### PR DESCRIPTION
**Pull request by gilluminate**

### CODE REVIEW

**Comment by vohof** [comment]
Hi, unfortunately listen on accepts a single argument which either is a port number or a hash of options.

**Comment by gilluminate** [comment]
interesting because if we add port:1234 as part of the hash of options it doesn't work. But if we list it like I've listed in this fix it does. Here's our exact setup which is working:

```javascript
    plug.livereload.listen(9000, {
        key: read('../Certificates/livereload/livereload.key'),
        cert: read('../Certificates/livereload/livereload.crt')
    });
```

**Comment by gilluminate** [comment]
oh, I see. It's actually the fact that we don't need to specify the key/cert for https to work that has me confused. It seems to simply work without.

**Comment by gilluminate** [comment]
nope. on second look I was wrong again. Unless I specify key and cert, https won't work. This example above is the only way to get it working on port 9000 over ssl.

**Comment by vohof** [comment]
That's weird, the `listen` function [does not accept a second argument](https://github.com/vohof/gulp-livereload/blob/master/index.js#L82). :thought_balloon:

**Comment by gilluminate** [comment]
Ok, I just realized I'm on the 2.x version. My bad.

**Comment by vohof** [comment]
Hehehe :space_invader:

**Pull request closed without merging**
